
theme = "monokai_pro"

[editor]
auto-format = true
true-color = true
bufferline = "always"
cursorline = true
rulers = [120]
end-of-line-diagnostics = "hint"
line-number = "relative"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "error"

[editor.indent-guides]
render = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true


[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
A-w = ":bc"
A-W = ":wbc"
A-tab = ":buffer-next"
A-S-tab = ":buffer-previous"
C-r = ":reload"
Cmd-p = "file_picker"
Cmd-S-p = "command_palette"
Cmd-S-f = "global_search"
Cmd-s = ":w"
