[language-server.efm-lsp-prettier]
command = "efm-langserver"


[language-server.rust-analyzer]
config = { checkOnSave = { command = "clippy" } }


[[language]]
auto-format = true
name = "rust"

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
language-servers = [
  { name = "efm-lsp-prettier", only-features = [
    "format",
  ] },
  "typescript-language-server",
]

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
language-servers = [
  { name = "efm-lsp-prettier", only-features = [
    "format",
  ] },
  "typescript-language-server",
]

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "bash"
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "jsonnet"
auto-format = true
