# Completion emitters for zarg, sourced on demand by `--completions SHELL`.
#
# Split out of the plugin because scripts source zarg on every invocation and
# only ever generate completions at converge time.
#
# Fidelity differs by shell, and that is the shells' doing: `complete=` names a
# zsh completion function, so only zsh honours it. fish and bash fall back to
# file completion there. Declared value sets (`values=`) work everywhere.

# _arguments specs are bracket- and colon-delimited, so anything in help text
# that looks like structure has to be neutralised.
_zarg_esc_zsh() {
  local s=${1//\'/\'\\\'\'}; s=${s//\[/\\[}; s=${s//\]/\\]}
  print -r -- "${s//:/\\:}"
}
_zarg_esc_fish() { print -r -- "${1//\'/\\\'}" }
_zarg_esc_bash() { local s=${1//\\/\\\\}; s=${s//\"/\\\"}; print -r -- "${s//\$/\\\$}" }

# The ":metavar:action" tail shared by zsh options and positionals.
_zarg_action_zsh() {
  local metavar=$1 values=$2 complete=$3
  if   [[ -n $values ]];   then print -r -- ":${metavar}:(${values})"
  elif [[ -n $complete ]]; then print -r -- ":${metavar}:${complete}"
  else                          print -r -- ":${metavar}: "
  fi
}

_zarg_comp_zsh() {
  local rec short long i=1
  local -a lines

  for rec in "$ZARG_FLAGS[@]"; do
    short=$(_zarg_f "$rec" 1) long=$(_zarg_f "$rec" 2)
    lines+=("'($short $long)'{$short,$long}'[$(_zarg_esc_zsh "$(_zarg_f "$rec" 3)")]'")
  done
  for rec in "$ZARG_OPTS[@]"; do
    short=$(_zarg_f "$rec" 1) long=$(_zarg_f "$rec" 2)
    lines+=("'($short $long)'{$short,$long}'[$(_zarg_esc_zsh "$(_zarg_f "$rec" 3)")]$(_zarg_action_zsh "$(_zarg_f "$rec" 9)" "$(_zarg_f "$rec" 7)" "$(_zarg_f "$rec" 8)")'")
  done
  for rec in "$ZARG_ARGS[@]"; do
    local action=$(_zarg_action_zsh "$(_zarg_f "$rec" 1)" "$(_zarg_f "$rec" 6)" "$(_zarg_f "$rec" 7)")
    if (( $(_zarg_f "$rec" 4) )); then lines+=("'*${action}'")
    else                               lines+=("'${i}${action}'"); (( i++ ))
    fi
  done

  print -r -- "#compdef $ZARG_NAME"
  print -r -- "# Generated by \`$ZARG_NAME --completions zsh\` — regenerate with \`task generate:completions\`."
  print -r -- ""
  print -r -- "_arguments -s \\"
  for (( i = 1; i <= $#lines; i++ )); do print -r -- "  ${lines[i]} \\"; done
  print -r -- "  '(-h --help)'{-h,--help}'[show help]' \\"
  print -r -- "  '--version[show version]' \\"
  print -r -- "  '--completions[emit completions]:shell:(zsh fish bash)'"
}

_zarg_comp_fish() {
  local rec values cond first=1

  print -r -- "# Generated by \`$ZARG_NAME --completions fish\` — regenerate with \`task generate:completions\`."

  for rec in "$ZARG_FLAGS[@]"; do
    print -r -- "complete -c $ZARG_NAME -s ${$(_zarg_f "$rec" 1)#-} -l ${$(_zarg_f "$rec" 2)#--} -d '$(_zarg_esc_fish "$(_zarg_f "$rec" 3)")'"
  done
  for rec in "$ZARG_OPTS[@]"; do
    values=$(_zarg_f "$rec" 7)
    print -rn -- "complete -c $ZARG_NAME -s ${$(_zarg_f "$rec" 1)#-} -l ${$(_zarg_f "$rec" 2)#--} -r -d '$(_zarg_esc_fish "$(_zarg_f "$rec" 3)")'"
    [[ -n $values ]] && print -rn -- " -a '$values'"
    print -r -- ""
  done

  # Only declared value sets are emitted. Everything else is left to fish's
  # default file completion, which is what an undeclared positional wants.
  for rec in "$ZARG_ARGS[@]"; do
    values=$(_zarg_f "$rec" 6)
    if (( first )) && (( ! $(_zarg_f "$rec" 4) )); then
      cond="-n __fish_is_first_arg"; first=0
    else
      cond=
    fi
    [[ -n $values ]] && \
      print -r -- "complete -c $ZARG_NAME $cond -a '$values' -d '$(_zarg_esc_fish "$(_zarg_f "$rec" 2)")'"
  done

  print -r -- "complete -c $ZARG_NAME -s h -l help -d 'show this help'"
  print -r -- "complete -c $ZARG_NAME -l version -d 'show version'"
  print -r -- "complete -c $ZARG_NAME -l completions -r -a 'zsh fish bash' -d 'emit completions'"
}

_zarg_comp_bash() {
  local rec fn=_${ZARG_NAME//[^a-zA-Z0-9]/_}
  local -a all
  local -a valued

  for rec in "$ZARG_FLAGS[@]"; do all+=("$(_zarg_f "$rec" 1)" "$(_zarg_f "$rec" 2)"); done
  for rec in "$ZARG_OPTS[@]"; do
    all+=("$(_zarg_f "$rec" 1)" "$(_zarg_f "$rec" 2)")
    valued+=("$(_zarg_f "$rec" 1)|$(_zarg_f "$rec" 2)${ZARG_SEP}$(_zarg_f "$rec" 7)")
  done
  all+=(-h --help --version --completions)

  print -r -- "# Generated by \`$ZARG_NAME --completions bash\` — regenerate with \`task generate:completions\`."
  print -r -- "$fn() {"
  print -r -- "  local cur prev"
  print -r -- '  cur="${COMP_WORDS[COMP_CWORD]}"'
  print -r -- '  prev="${COMP_WORDS[COMP_CWORD-1]}"'
  print -r -- '  case "$prev" in'
  print -r -- "    --completions) COMPREPLY=(\$(compgen -W \"zsh fish bash\" -- \"\$cur\")); return ;;"
  for rec in "$valued[@]"; do
    local pair=${rec%%${ZARG_SEP}*} values=${rec#*${ZARG_SEP}}
    [[ -n $values ]] || continue
    print -r -- "    $pair) COMPREPLY=(\$(compgen -W \"$(_zarg_esc_bash "$values")\" -- \"\$cur\")); return ;;"
  done
  print -r -- '  esac'
  print -r -- '  if [[ $cur == -* ]]; then'
  print -r -- "    COMPREPLY=(\$(compgen -W \"${all[*]}\" -- \"\$cur\")); return"
  print -r -- '  fi'

  # Positional value sets, when the first one declares them.
  local firstvals=
  for rec in "$ZARG_ARGS[@]"; do firstvals=$(_zarg_f "$rec" 6); break; done
  if [[ -n $firstvals ]]; then
    print -r -- "  if (( COMP_CWORD == 1 )); then"
    print -r -- "    COMPREPLY=(\$(compgen -W \"$(_zarg_esc_bash "$firstvals")\" -- \"\$cur\")); return"
    print -r -- "  fi"
  fi
  print -r -- '  COMPREPLY=($(compgen -f -- "$cur"))'
  print -r -- "}"
  print -r -- "complete -F $fn $ZARG_NAME"
}

zarg_completions() {
  case $1 in
    zsh)  _zarg_comp_zsh ;;
    fish) _zarg_comp_fish ;;
    bash) _zarg_comp_bash ;;
    *) print -ru2 -- "$ZARG_NAME: unknown shell '$1' (want: zsh, fish, bash)"; return 1 ;;
  esac
}
