# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[directory]
truncation_length = 8
truncate_to_repo = false
style = "fg:8"
truncation_symbol = "…/"

[git_branch]
symbol = "  "
format = "[$symbol$branch]($style) "
style = "green"

[aws]
symbol = "  "
format = '[$symbol$profile(\($region\))]($style) '
style = "yellow"

[gcloud]
disabled = true
symbol = " "
format = '[$symbol$account(\($region\))]($style) '

[nodejs]
symbol = " "
disabled = true
style = "green"
