tap "bufbuild/buf"
tap "buo/cask-upgrade"
tap "cloudflare/cloudflare"
tap "facebook/fb"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "nanovms/ops"
tap "nanovms/qemu"
tap "withgraphite/tap"
tap "metalbear-co/mirrord"
brew "ansible"
brew "ansible-language-server"
brew "ansible-lint"
brew "argocd"
brew "aria2"
brew "aws-shell"
brew "aws-sso-util"
brew "aws-vault"
brew "awscli"
brew "azure-cli"
brew "bat"
brew "broot"
brew "clang-format"
brew "cloudflare/cloudflare/cf-terraforming"
brew "cmake"
brew "cmatrix"
brew "cmus"
brew "coreutils"
brew "curl"
brew "metalbear-co/mirrord/mirrord"
brew "elixir-ls"
brew "evans"
brew "fastfetch"
brew "fcp"
brew "ffmpeg"
brew "findutils"
brew "fish"
brew "fzf"
brew "gh"
brew "grpcurl"
brew "git"
brew "git-lfs"
brew "gmp"
brew "gnupg"
brew "hashicorp/tap/terraform"
brew "helix"
brew "htop"
brew "hyperfine"
brew "ios-deploy"
brew "iperf3"
brew "jsonnet"
brew "k9s"
brew "libpq"
brew "libyaml"
brew "llvm"
brew "lsd"
brew "lsix"
brew "luarocks"
brew "macchina"
brew "make"
brew "mas"
brew "mise"
brew "nanovms/ops/ops"
brew "nmap"
brew "node"
brew "openssl@3"
brew "ossp-uuid"
brew "parallel"
brew "postgresql"
brew "pulumi"
brew "qemu"
brew "rclone"
brew "readline"
brew "ripgrep"
brew "rsync"
brew "sheldon"
brew "starship"
brew "syncthing"
brew "taplo"
brew "telnet"
brew "terraform"
brew "terraform-ls"
brew "testdisk"
brew "tig"
brew "tmux"
brew "tpm"
brew "tree"
brew "ttfautohint"
brew "unbound"
brew "vercel-cli"
brew "vscode-langservers-extracted"
brew "watchman"
brew "wget"
brew "whalebrew"
brew "withgraphite/tap/graphite"
brew "wrk"
brew "xz"
brew "yaml-language-server"
brew "zoxide"
brew "zsh"
cask "1password"
cask "1password-cli"
cask "discord"
cask "beekeeper-studio"
cask "figma"
cask "firefox"
cask "focusrite-control"
cask "foobar2000"
cask "fork"
cask "ghostty"
cask "lens"
cask "notion"
cask "notion-calendar"
cask "orbstack"
cask "rar"
cask "stolendata-mpv", args: { no_quarantine: true }
cask "zed"
cask "zed@preview"
cask "zen-browser"
# mas "1Password for Safari", id: 1569813296
# mas "Adobe Lightroom", id: 1451544217
# mas "Infuse", id: 1136220934
# mas "Messenger", id: 1480068668
# mas "Slack", id: 803453959
# mas "Tailscale", id: 1475387142
# mas "Telegram", id: 747648890
# mas "WhatsApp", id: 310633997

# Added by go-brew-search on 2025-05-26 14:08:07
cask "font-inconsolata-nerd-font"

# Added by go-brew-search on 2025-05-26 14:09:26
brew "ruby" # Powerful, clean, object-oriented scripting language

# Added by go-brew-search on 2025-05-26 17:32:35
brew "golangci-lint" # Fast linters runner for Go
