version: '3.8'

services:
  dev-shell:
    build: .
    image: dotfiles-dev:latest
    container_name: dev-shell
    stdin_open: true
    tty: true
    working_dir: /home/dev/workspace
    volumes:
      # Mount workspace
      - ./workspace:/home/dev/workspace
      # Persist shell history and config
      - zsh-history:/home/dev/.zsh_history
      - mise-cache:/home/dev/.local/share/mise
    ports:
      - "3000:3000"
      - "3001:3001" 
      - "4000:4000"
      - "5000:5000"
      - "8000:8000"
      - "8080:8080"
    environment:
      - TERM=xterm-256color
    networks:
      - dev-network

volumes:
  zsh-history:
  mise-cache:

networks:
  dev-network:
    driver: bridge