#!/bin/sh
cd "$(dirname "$0")" || exit
DOTFILES=$(pwd)
git pull
echo "export DOTFILES=$DOTFILES" >~/.dotfiles-dir

link_dotfile() {
  if [ -h "$HOME/$1" ]; then
    echo "skipping $1 (link) "
    return
  fi
  if [ -f "$HOME/$1" ]; then
    echo "skipping $1 (file) "
    return
  fi
  if [ -d "$HOME/$1" ]; then
    echo "skipping $1 (dir) "
    return
  fi
  if [ ".config" = "$1" ]; then
    echo "skipping $1 (.config) "
    return
  fi

  case "$1" in
  *.git | .gitignore | ".|.." | .vscode | .sonarlint) return ;;
  esac

  echo "$PWD/$1"

  echo "linking $PWD/$1 -> $HOME/$1"
  ln -s "$PWD/$1" "$HOME/$1"
}

link_confdir() {
  if [ ! -d "$HOME/.config" ]; then
    echo "creating ~/.config"
    mkdir "$HOME/.config"
  fi
  if [ -d "$HOME/.config/$1" ]; then
    echo "skipping ~/.config/$1 (exists) "
    return
  fi
  echo "linking $PWD/$1 --> ~/.config/$1"
  ln -s "$PWD/$1" "$HOME/.config/$1"
}

install_dotfiles() {
  . "$HOME/.dotfiles-dir"
  [ ! -d "$DOTFILES" ] && return
  echo "installing from $DOTFILES..."
  (
    cd "$DOTFILES" || exit
    for file in .*; do
      link_dotfile "$file"
    done

    (
      cd config || exit
      for confdir in *; do
        link_confdir "$confdir"
      done
    )
  )
}

install_brewfile() {
  if [ -d /Library ] && [ ! -f "$HOME/Brewfile" ]; then
    echo "linking Brewfile $DOTFILES/Brewfile -> ~/Brewfile"
    ln -s "$DOTFILES/Brewfile" "$HOME/Brewfile"
  fi
}

install_dotfiles "$DOTFILES"
install_brewfile
