apiVersion: v1
kind: Namespace
metadata:
  name: dev-shell
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-workspace-pvc
  namespace: dev-shell
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-shell
  namespace: dev-shell
  labels:
    app: dev-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-shell
  template:
    metadata:
      labels:
        app: dev-shell
    spec:
      containers:
      - name: dev-shell
        image: ghcr.io/radiosilence/dotfiles/dev-shell:container
        stdin: true
        tty: true
        workingDir: /home/dev/workspace
        ports:
        - containerPort: 3000
          name: dev-3000
        - containerPort: 3001
          name: dev-3001
        - containerPort: 8000
          name: dev-8000
        - containerPort: 8080
          name: dev-8080
        env:
        - name: TERM
          value: "xterm-256color"
        volumeMounts:
        - name: workspace
          mountPath: /home/dev/workspace
        - name: zsh-history
          mountPath: /home/dev/.zsh_history
          subPath: zsh_history
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: dev-workspace-pvc
      - name: zsh-history
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dev-shell-service
  namespace: dev-shell
spec:
  selector:
    app: dev-shell
  ports:
  - name: dev-3000
    port: 3000
    targetPort: 3000
  - name: dev-3001
    port: 3001
    targetPort: 3001
  - name: dev-8000
    port: 8000
    targetPort: 8000
  - name: dev-8080
    port: 8080
    targetPort: 8080
  type: ClusterIP