directory: /Volumes/Turtlehead/music
asciify_paths: false
original_date: true
per_disc_numbering: true
import:
  move: true
  copy: false
paths:
  default: $albumartist/%if{$year,($year) }$album%aunique{} [$format]/$disc$track. $artist - $title
  comp: Various Artists/$album%aunique{} [$format]/$disc$track. $artist - $title
plugins:
  - ftintitle
  - discogs
  - fetchart
  - embedart
  - importadded
  - yearfixer
discogs:
  index_tracks: true
replace:
  '[\\/]': "-"
  '^\.': "-"
  '[\x00-\x1f]': "-"
  '[<>:"\?\*\|]': "-"
  '\.$': "-"
  '\s+$': ""
  '^\s+': ""
  "^-": "-"
