asciify_paths: false
original_date: true
per_disc_numbering: true
import:
  move: true
  copy: false
paths:
  default: $albumartist/%if{$year,($year) }$album%aunique{} [$format]/$disc$track. $artist - $title
  comp: Various Artists/$album%aunique{} [$format]/$disc$track. $artist - $title
plugins:
  - musicbrainz
  - ftintitle
  - fetchart
  - discogs
  - embedart
  - importadded
  - yearfixer
  - bestjpeg
pluginpath:
  - ~/.config/beets/plugins
discogs:
  index_tracks: true
fetchart:
  auto: true
  minwidth: 500
  maxwidth: 1200
  quality: 95
  enforce_ratio: 10%
  high_resolution: true
embedart:
  auto: true
  maxwidth: 1200
  quality: 95
  remove_art_file: true
replace:
  '[\\/]': "-"
  '^\.': "-"
  '[\x00-\x1f]': "-"
  '[<>:"\?\*\|]': "-"
  '\.$': "-"
  '\s+$': ""
  '^\s+': ""
  "^-": "-"
