#!/usr/local/bin zsh

# pure power
PURE_POWER_MODE=fancy
source ~/.purepower

# powerlevel9k
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='grey58'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='grey58'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='grey42'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='grey42'

