# aliases
alias youtube-'dl=noglob youtube-dl '
alias curl='noglob curl '
alias http='noglob http '
alias ip='ip -c -br '
alias brewski='brew update && brew upgrade && brew cask upgrade && brew cleanup; brew doctor '
alias zoom='sudo launchctl unload /Library/LaunchDaemons/com.cylance.cyoptics_service.plist'
alias szrc='source ~/.zshrc'
alias k='k --no-vcs -A -h '
alias html2pdf='docker run --rm -v $(pwd):/converted/ arachnysdocker/athenapdf athenapdf '
