alias yt='yarn test '
alias ytu='yarn test -u '
alias yr='yarn remove '
alias ya='yarn add '
alias yaW='yarn add -W '
alias yaD='yarn add -D '
alias yaDW='yarn add -DW '
alias ys='yarn && yarn start '
