add_newline = false

[character]
error_symbol = ""
success_symbol = ""

[directory]
truncation_length = 8
truncate_to_repo = false
style = "fg:8"
truncation_symbol = ".../"

[hostname]
format = "[$hostname]($style) "

[username]
format = "[$user]($style)@"
show_always = false

[git_branch]
symbol = "  "
format = "[$symbol$branch]($style) "
style = "green"

[aws]
symbol = "  "
format = '[$symbol$profile(\($region\))]($style) '
style = "yellow"

[gcloud]
disabled = true
symbol = " "
format = '[$symbol$account(\($region\))]($style) '

[nodejs]
symbol = " "
disabled = false
style = "green"

[kotlin]
disabled = false

[java]
disabled = false

[package]
disabled = true
display_private = true
symbol = "  "
