add_newline = false

format = """
$username\
$hostname\
$localip\
$singularity\
$kubernetes\
$directory\
${custom.git_email}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$container\
$elixir\
$gleam\
$golang\
$kotlin\
$lua\
$nodejs\
$pulumi\
$python\
$ruby\
$rust\
$terraform\
$buf\
$memory_usage\
$aws\
$nats\
$direnv\
$env_var\
$mise\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$os\

$shell\
$character
"""

[character]
error_symbol = ""
success_symbol = ""

[directory]
truncation_length = 8
truncate_to_repo = false
read_only = ""
style = "fg:8"
truncation_symbol = ".../"

[hostname]
format = "[$hostname]($style) "

[username]
format = "[$user]($style)@"
show_always = false

[custom.git_email]
when = true
format = "[ $output]($style) "
style = "dim"
shell = ["git", "config", "user.email"]

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "green"

[docker_context]
disabled = true

[container]
format = " "
disabled = false

[golang]
symbol = "󰟓 "

[nodejs]
symbol = " "
disabled = false
style = "green"


[package]
disabled = true
display_private = true
symbol = "  "