add_newline = false

format = """
$username\
$hostname\
$directory\
${custom.git_email}\
$git_branch\
$gcloud\
$nodejs\
$kotlin\
$java\
$package\
$character\
"""

[character]
error_symbol = ""
success_symbol = ""

[directory]
truncation_length = 8
truncate_to_repo = false
style = "fg:8"
truncation_symbol = ".../"

[hostname]
format = "[$hostname]($style) "

[username]
format = "[$user]($style)@"
show_always = false

[custom.git_email]
symbol = ""
command = "git config user.email"
when = "git rev-parse --is-inside-work-tree"
format = "[ $output]($style) "
style = "dim"

[git_branch]
symbol = "  "
format = "[$symbol$branch]($style) "
style = "green"


[gcloud]
disabled = true
symbol = " "
format = '[$symbol$account(\($region\))]($style) '

[nodejs]
symbol = " "
disabled = false
style = "green"

[kotlin]
disabled = false

[java]
disabled = false

[package]
disabled = true
display_private = true
symbol = "  "
