[tool_alias]
aube = "github:endevco/aube"
bat = "github:sharkdp/bat"
broot = "github:Canop/broot"
codeowners-lsp = "github:radiosilence/codeowners-lsp"
delta = "github:dandavison/delta"
fastfetch = "github:fastfetch-cli/fastfetch"
fastmail-cli = "github:radiosilence/fastmail-cli"
fd = "github:sharkdp/fd"
fzf = "github:junegunn/fzf"
git-lfs = "github:git-lfs/git-lfs"
glow = "github:charmbracelet/glow"
helix = "github:helix-editor/helix"
hyperfine = "github:sharkdp/hyperfine"
jq = "github:jqlang/jq"
koan = "github:radiosilence/koan"
kubecolor = "github:kubecolor/kubecolor"
lsd = "github:lsd-rs/lsd"
nano-web = "github:radiosilence/nano-web"
ni = "npm:@antfu/ni"
oha = "github:hatoo/oha"
pnpm-shell-completion = "github:g-plane/pnpm-shell-completion"
procs = "github:dalance/procs"
pup = "github:datadog-labs/pup"
ripgrep = "github:BurntSushi/ripgrep"
sfw-free = "github:SocketDev/sfw-free"
sheldon = "github:rossmacarthur/sheldon"
snowflake-cli = "pipx:snowflake-cli"
squawk = "github:sbdchd/squawk"
starship = "github:starship/starship"
taplo = "github:tamasfe/taplo"
task = "github:go-task/task"
watchwoman = "github:radiosilence/watchwoman"
xh = "github:ducaale/xh"
yq = "github:mikefarah/yq"
yt-dlp = "github:yt-dlp/yt-dlp-nightly-builds"
zellij = "github:zellij-org/zellij"
zoxide = "github:ajeetdsouza/zoxide"
zsh-patina = "github:michel-kraemer/zsh-patina"
