[tool_alias]
broot = "github:Canop/broot"
codeowners-lsp = "github:radiosilence/codeowners-lsp"
fastfetch = "github:fastfetch-cli/fastfetch"
fastmail-cli = "github:radiosilence/fastmail-cli"
koan = "github:radiosilence/koan"
nano-web = "github:radiosilence/nano-web"
pnpm-shell-completion = "github:g-plane/pnpm-shell-completion"
procs = "github:dalance/procs"
pup = "github:datadog-labs/pup"
sfw-free = "github:SocketDev/sfw-free"
snowflake-cli = "pipx:snowflake-cli"
watchwoman = "github:radiosilence/watchwoman"
zsh-patina = "github:michel-kraemer/zsh-patina"
