[tool_alias]
aria2 = "github:radiosilence/aria2"
beets = "pipx:beets[uvx_args=--with requests --with beets-yearfixer --with beets[discogs]]"
broot = "github:Canop/broot"
caldav = "github:radiosilence/caldav-cli"
codeowners-lsp = "github:radiosilence/codeowners-lsp"
dexter = "aqua:remoteoss/dexter"
fastfetch = "github:fastfetch-cli/fastfetch"
fastmail = "github:radiosilence/fastmail-cli"
koan = "github:radiosilence/koan"
mainlynorfolk = "github:radiosilence/mainlynorfolk-mcp"
nano-web = "github:radiosilence/nano-web"
omp = "github:can1357/oh-my-pi"
pnpm-shell-completion = "github:g-plane/pnpm-shell-completion"
procs = "github:dalance/procs"
pup = "github:datadog-labs/pup"
sfw-free = "github:SocketDev/sfw-free"
snowflake-cli = "pipx:snowflake-cli"
suvadu = "github:AppachiTech/suvadu"
tfl = "github:radiosilence/tfl-mcp"
watchwoman = "github:radiosilence/watchwoman"
zsh-patina = "github:michel-kraemer/zsh-patina"
