version: '3'

tasks:
  build:
    desc: Build the Swift application
    cmds:
      - swiftc -o browser-schedule-swift main.swift
    sources:
      - main.swift
    generates:
      - browser-schedule-swift

  test:
    desc: Test the application with a URL
    deps: [build]
    cmds:
      - ./browser-schedule-swift http://test.com
      - tail -5 /tmp/browser-schedule.log

  test-work:
    desc: Test during work hours (simulate by checking current time)
    deps: [build]  
    cmds:
      - ./browser-schedule-swift http://test-work.com
      - tail -5 /tmp/browser-schedule.log

  install:
    desc: Install the app bundle as default browser
    deps: [build]
    cmds:
      - ./browser-schedule-swift --install
      - defaultbrowser browserschedule

  update:
    desc: Update the app bundle with current config
    deps: [build]
    cmds:
      - ./browser-schedule-swift --update

  uninstall:
    desc: Remove the app bundle and reset default browser
    cmds:
      - defaultbrowser safari
      - rm -rf /Applications/BrowserSchedule.app

  status:
    desc: Show current status  
    cmds:
      - |
        if [ -d "/Applications/BrowserSchedule.app" ]; then
          echo "Status: Installed"
          if defaultbrowser | grep -q "browserschedule"; then
            echo "  Default browser: ✓ Set as default"
          else
            echo "  Default browser: ✗ Not set as default"
          fi
        else
          echo "Status: Not installed"
        fi

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f browser-schedule-swift

  logs:
    desc: Show recent logs
    cmds:
      - tail -20 /tmp/browser-schedule.log

  config:
    desc: Show current config
    deps: [build]
    cmds:
      - ./browser-schedule-swift --config